from Trabajador import Trabajador
from Boleta import Boleta
Trabajador1=Trabajador("Roberto Carlos")
Boleta1=Boleta("B",10,200)
print("***DATOS DE ENTRADA***")
print() 
Trabajador1.nombre_trabajador() 
Boleta1.Categoria()
Boleta1.Horas_extras()
Boleta1.tardanza()
print() 
print("***BOLETA DE PAGO***")
print() 
Trabajador1.nombre_trabajador()  
Boleta1.Categoria()
Boleta1.sueldo()
Boleta1.descuento()
Boleta1.extra()
Boleta1.total()